import { Category, Product, BlogPost } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Orthopedic Dog Bed',
    description: 'Relieves joint pain and provides ultimate comfort for dogs of all sizes.',
    price: '$59.99',
    rating: 4.8,
    reviewsCount: 1250,
    image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=400',
    category: Category.DOG_ACCESSORIES,
    features: ['Memory foam base', 'Machine washable cover', 'Waterproof liner'],
    pros: ['Excellent support', 'Non-slip bottom', 'Durable fabric'],
    cons: ['Slight off-gassing initial smell', 'Takes 24h to fully expand'],
    amazonUrl: '#',
    fullReview: 'The Orthopedic Dog Bed is a top-tier choice for aging pets. After testing it with our 10-year-old Labrador, we noticed a significant improvement in his morning mobility...',
  },
  {
    id: '2',
    name: 'Interactive Laser Cat Toy',
    description: 'Keep your indoor cat entertained for hours with random patterns.',
    price: '$24.99',
    rating: 4.5,
    reviewsCount: 890,
    image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&q=80&w=400',
    category: Category.CAT_TOYS,
    features: ['USB Rechargeable', '3 speed settings', 'Auto-shutoff timer'],
    pros: ['Hands-free entertainment', 'Quiet operation', 'Effective for exercise'],
    cons: ['Needs frequent recharging on fast mode', 'Laser can be hard to see in bright rooms'],
    amazonUrl: '#',
    fullReview: 'If you have a high-energy indoor cat, this laser toy is a lifesaver. It features a sleek design that fits into any modern home decor...',
  },
  {
    id: '3',
    name: 'Heavy Duty Dog Harness',
    description: 'No-pull pet harness with adjustable straps and reflective trim.',
    price: '$29.99',
    rating: 4.9,
    reviewsCount: 2100,
    image: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?auto=format&fit=crop&q=80&w=400',
    category: Category.DOG_ACCESSORIES,
    features: ['Front and back clips', 'Breathable mesh', 'Escape-proof design'],
    pros: ['Sturdy construction', 'Great control', 'Comfortable padding'],
    cons: ['Buckles can be stiff', 'Measurement guide is slightly off'],
    amazonUrl: '#',
    fullReview: 'Walking a puller can be stressful. We tested this harness on a rambunctious Golden Retriever and the difference was night and day...',
  },
  {
    id: '4',
    name: 'Self-Cleaning Cat Litter Box',
    description: 'Say goodbye to scooping with this smart odor-control litter box.',
    price: '$399.00',
    rating: 4.7,
    reviewsCount: 450,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=400',
    category: Category.CAT_ACCESSORIES,
    features: ['App connected', 'Odor elimination system', 'Whisper quiet'],
    pros: ['Saves time', 'Eliminates smell completely', 'Detailed pet health tracking'],
    cons: ['Expensive upfront cost', 'Requires specific litter type'],
    amazonUrl: '#',
    fullReview: 'Yes, it is pricey. But is it worth it? After a month of zero scooping, our answer is an enthusiastic yes...',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Top 10 Must-Have Dog Products in 2026',
    excerpt: 'From smart collars to eco-friendly poop bags, here is what every modern dog owner needs this year.',
    content: 'Content goes here...',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=400',
    date: 'April 15, 2026',
  },
  {
    id: 'b2',
    title: 'Best Budget Cat Toys That Cats Actually Love',
    excerpt: 'You don\'t have to spend a fortune. Here are the top cheap toys that will beat out an empty cardboard box.',
    content: 'Content goes here...',
    image: 'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?auto=format&fit=crop&q=80&w=400',
    date: 'April 10, 2026',
  },
  {
    id: 'b3',
    title: 'How to Choose the Right Dog Harness',
    excerpt: 'Stop the pulling! A comprehensive guide to finding the perfect fit and style for your dog\'s breed.',
    content: 'Content goes here...',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=400',
    date: 'April 5, 2026',
  },
];
